aave/aip

- src/components/MobileMenu/index.js
> Revert "fixed: gatsby build"

- content/aips/AIP-gusd.md
Corresponding AIP for adding GUSD support: https://governance.aave.com/t/proposal-add-support-for-gemini-gusd/384
> Add AIP-gusd.md

- content/aips/AIP-Add-BAL.md
> Add BAL to AAVE

- content/aips/AIP-12.md
- content/aips/AIP-aAMPL.md
Corresponding AIP for adding AMPL support: https://governance.aave.com/t/proposal-add-support-for-ampl/854
> Create AIP-12.md for aAMPL

- content/aips/AIP-28.md
- content/ipfs-aips/AIP-28-Ipfs-hashes.json
Minor updates to status and description fields
> Pending ai ps

- content/aips/AIP-35.md
> AIP 35: Adjust interest rate to account for APY over-approximation

- content/aips/4C7076AA6CC7-AIP-FIREBLOCKS-WHITELISTER-ON-AAVE-ARC.md
> Fireblocks AIP - Updates

- content/aips/C80DBB8511E8-AIP-Optimizing-ETH-rates.md
Updating the rates of WETH.
[Here](https://etherscan.io/address/0xEc368D82cb2ad9fc5EfAF823B115A622b52bcD5F#code) is the new interest rate contracts.
> Optimizing ETH rates

- content/aips/8E70B487F248-AIP-CONSOLIDATE-RESERVE-FACTORS-ENABLE-DPI.md
The AIP describing Aave V1 and V2 reserve factor refactors and enabling the borrowing of DPI
> Consolidate Reserve Factors and Enable Borrowing DPI

- content/aips/4B301050BD35-AIP-ADD-STMATIC-TO-AAVE-V3-POLYGON.md
- content/aips/C31C23077214-AIP-ADD-STMATIC-TO-AAVE-V3-POLYGON.md
This includes an AIP listing stMATIC on AAVE v3 on Polygon.
More details can be found on the governance forum: https://governance.aave.com/t/proposal-add-support-for-stmatic-lido/7677
> Add stMATIC to Aave v3 market on Polygon

- content/aips/35A56F18FEFC-AIP-REDEEM-AFEI-FOR-DAI.md
- content/aips/7CDA90A3999E-AIP-REDEEM-AFEI-FOR-DAI.md
This includes an AIP describing the aFEI Holding Update for the Ethereum v2 Reserve Factor.
More details can be found on the governance forum: https://governance.aave.com/t/arc-ethereum-v2-reserve-factor-afei-holding-update/9401
> Ethereum v2 Reserve Factor - aFEI Holding Update

- content/aips/4A7DEC60B007-AIP-AAVE-LLAMA.md
This includes an AIP for the Llama <> Aave Proposal.
More details can be found on the governance forum: https://governance.aave.com/t/updated-proposal-llama-aave/9924
> Llama <> Aave

- content/aips/C21F601D0D3F-AIP-STKAAVE-RETRIEVAL.md
This includes an AIP to set the claimer of Balancer DAO's rewards to be the retrieval contract 
More details can be found on the governance forum: https://governance.aave.com/t/arc-whitelist-balancer-s-liquidity-mining-claim/9724
> StkAave Retrieval for Balancer DAO

- content/aips/3D16C7B29565-AIP-FEI-RESERVE-FACTOR-UPDATE.md
This includes an AIP for the Fei Reserve Factor Update
More details can be found on the governance forum: https://governance.aave.com/t/bgd-aave-v2-ethereum-fei-security-report/10251
> Fei Reserve Factor Update

- content/aips/CHAOS-LABS-RISK-PLATFORM-PROPOSAL.md
> chaos-payload-address

- content/aips/100K-BAL-ACQUISITION.md
- content/aips/58D30E766E47-AIP-100K-BAL-ACQUISITION.md
This includes an AIP for the 100k BAL Acquisition as part of Strategic Partnership with Balancer DAO Part 2
More details can be found on the governance forum: https://governance.aave.com/t/arc-strategic-partnership-with-balancer-part-2/7813
> 100k BAL Acquisition

- X-AIP.md
I'd like to propose simplifying the template so it's not overwhelming and ppl can actually follow it.
> docs: improve template

- content/aips/CHAOS-LABS-AAVE-V2-COVERAGE.md
Chaos Labs AIP for V2 Coverage
> Chaos Labs V2 Coverage AIP

- content/aips/AGD-RENEWAL-JAN-2023.md
AIP for Aave Grants DAO renewal.
Forum post: https://governance.aave.com/t/updated-proposal-aave-grants-dao-renewal/11289
Snapshot: https://snapshot.org/#/aave.eth/proposal/0x194b68a5319b074065e38fcb0bd96e8e8b6ce15870844593e79750605a609109
> AGD-RENEWAL-JAN-2023

- content/aips/LDO-EMISSION-ADMINS.md
Add LDO Emission admin AIP.
Governance post: https://governance.aave.com/t/arfc-ldo-emission-admin-for-ethereum-arbitrum-and-optimism-v3-liquidity-pools/11478
> LDO Emission Admin Updates

- content/aips/V2-ETH-WETH-STRATEGY-UPDATE.md
Add AIP for updating wETH pool interest rate strategy.
> Ethereum v2 wETH Interest Rate Strategy AIP

- content/aips/WSTETH-ARBITRUM-LISTING.md
Add AIP for wstETH listing on Aave V3 Arbitrum.
> wstETH Arbitrum Listing

- content/aips/MATICX-RISK-PARAMETERS.md
**Pending Review and links
Update MaticX parameters on Polygon V3 Liquidity Pool.
> MaticX Polygon Risk Parameter Updates (draft)

- content/aips/AAVE-V3-ETHEREUM-CRV-LISTING.md
**Pending Code Review**
Add CRV as an asset on Aave v3 Ethereum.
> Aave v3 Ethereum CRV Listing

- content/aips/CRV-INTEREST-RATES.md
Add AIP to update interest rate strategies for CRV in the Ethereum v2, Polygon v2 and Polygon v3 pools.
Update supply cap for CRV on Polygon v3 pool.
> CRV Interest Rate Updates

- content/aips/MATICX-SUPPLY-CAP-03132023.md
> Aave Polygon v3: MaticX Supply Cap Increase

- content/aips/LUSD_ETH_V3_CAP_UPDATE.md
Discussion: https://governance.aave.com/t/arfc-supply-and-borrow-caps-update-lusd-v3-ethereum/12289
> AIP - LUSD supply caps update ethereum v3

- content/aips/AAVE-V3-OPTIMISM-OP-REWARDS-EMISSION-ADMIN.md
Add OP rewards Emission admin AIP.
> Aave V3 Optimism: OP Rewards Emission Admin (draft)

- content/aips/AIP-SUPPLY-CAPS-POLYGON-ARBITRUM-V3.md
discussions:
https://governance.aave.com/t/arfc-supply-and-borrow-caps-update-wsteth-v3-arbitrum/12309
https://governance.aave.com/t/arfc-chaos-labs-supply-and-borrow-cap-updates-aave-v3-polygon-2023-03-16/12310
> AIP - wstETH, MAI, stMATIC supply caps update Polygon/Arbitrum v3 

- content/aips/AIP-FREEZE-DPI-V2-ETH.md
discussion: https://governance.aave.com/t/arfc-add-dpi-to-v3-ethereum-and-freeze-on-v2-ethereum/12354
> AIP - freeze DPI v2

- content/aips/20230312-UNI-MKR-SNX-BAL-LISTINGS.md
Add AIP to list UNI, MKR, SNX and BAL on Aave v3 Ethereum.
> Aave V3 Ethereum: UNI, MKR, SNX, BAL Listings (draft)

- content/aips/AIP-SUPPLY-CAPS-ARBITRUM-V3-20230330.md
discussion: https://governance.aave.com/t/arfc-chaos-labs-supply-and-borrow-cap-updates-03-30-2023/12532
> Arbitrum V3 caps update AIP

- content/aips/20230403-AAVE-V3-POL-WMATIC-CAPS-UPDATE.md
Add AIP for wMATIC supply cap update.
> Aave V3 Polygon: wMATIC Supply Cap Update

- content/aips/CHAOS-LABS-RISK-PARAMS-POLY-23-04.md
Risk Parameter Updates for WBTC, DAI, LINK and WMATIC
> Chaos Labs Risk Parameter Updates - Aave V3 Polygon - 2023.04.23

- content/aips/CHAOS-LABS-ENS-LISTING-ETH-V3-20230517.md
Discussion: https://governance.aave.com/t/arfc-add-ens-to-aave-v3-ethereum/13044
> AIP to Add ENS to Aave V3 Ethereum

- content/aips/CHAOS-LABS-RISK-PARAMS-ETH-20230529.md
Discussion: https://governance.aave.com/t/arfc-chaos-labs-risk-parameter-updates-aave-v3-ethereum-2023-05-18/13128
> Ethereum V3 Risk Parameters Update

- content/aips/AAVE-V3-ARBITRUM-RETH-LISTING.md
Add AIP to list rETH on Aave V3 Arbitrum.
> Aave V3 Arbitrum: List rETH
